In [2]:
import pandas as pd
import numpy as np

In [3]:
movies = pd.read_csv('datasets/tmdb_5000_movies.csv')
credits = pd.read_csv('datasets/tmdb_5000_credits.csv')

In [4]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies.shape

(4809, 23)

In [7]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.duplicated().sum()

np.int64(0)

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
import ast

In [14]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [15]:
movies['genres'] = movies.genres.apply(convert)

In [16]:
movies['keywords'] = movies.keywords.apply(convert)

In [17]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [18]:
def convert_cast(obj):
    L = []
    count = 0
    for i in ast.literal_eval(obj):
        if count != 3:
            L.append(i['name'])
            count+=1
        else:
            break
    return L

In [19]:
movies['cast'] = movies.cast.apply(convert_cast)

In [20]:
def convert_crew(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            
            break
    return L

In [21]:
movies['crew'] = movies.crew.apply(convert_crew)

In [22]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [23]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [24]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [25]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [26]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

In [27]:
movies['tags'] = movies['overview']  + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [28]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [29]:
new_df = movies[['movie_id','title','tags']]

In [30]:
new_df['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [31]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\ATHARV\AppData\Local\Temp\ipykernel_12864\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [32]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [33]:
pip install nltk

Requirement already satisfied: nltk in c:\users\atharv\appdata\local\programs\python\python314\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\atharv\appdata\local\programs\python\python314\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\atharv\appdata\local\programs\python\python314\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\atharv\appdata\local\programs\python\python314\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in c:\users\atharv\appdata\local\programs\python\python314\lib\site-packages (from nltk) (4.68.1)
Requirement already satisfied: colorama in c:\users\atharv\appdata\local\programs\python\python314\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
import nltk

In [35]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [36]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [37]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\ATHARV\AppData\Local\Temp\ipykernel_12864\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [39]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [40]:
vectors[2]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [41]:
feature_name = cv.get_feature_names_out()

In [42]:
feature_name[:500]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '18thcenturi', '19', '1910', '1920',
       '1930', '1940', '1944', '1950', '1950s', '1960', '1960s', '1970',
       '1970s', '1971', '1974', '1976', '1980', '1985', '1990', '1999',
       '19th', '19thcenturi', '20', '200', '2003', '2009', '20th', '21st',
       '23', '24', '25', '30', '300', '3d', '40', '50', '500', '60', '70',
       '80', 'aaron', 'aaroneckhart', 'abandon', 'abduct',
       'abigailbreslin', 'abil', 'abl', 'aboard', 'abov', 'abus',
       'academ', 'academi', 'accept', 'access', 'accid', 'accident',
       'acclaim', 'accompani', 'accomplish', 'account', 'accus', 'ace',
       'achiev', 'acquaint', 'act', 'action', 'actionhero', 'activ',
       'activist', 'activities', 'actor', 'actress', 'actual', 'ad',
       'adam', 'adamsandl', 'adamshankman', 'adapt', 'add', 'addict',
       'adjust', 'admir', 'admit', 'adolesc', 'adopt', 'ador',
       'adrienbrodi', 'adult', 'adultanim', 'adulteri', 'adulthood',
       'advanc', 'adventur', 'adventure', 'adventures', 'advertis',
       'advic', 'advis', 'affair', 'affect', 'afghanistan', 'africa',
       'african', 'africanamerican', 'aftercreditssting', 'afterlif',
       'aftermath', 'ag', 'age', 'agediffer', 'agenc', 'agency', 'agenda',
       'agent', 'agents', 'aggress', 'ago', 'agre', 'ahead', 'aid',
       'aidanquinn', 'ail', 'aim', 'air', 'airplan', 'airplanecrash',
       'airport', 'aka', 'al', 'alabama', 'alan', 'alaska', 'albert',
       'alcatraz', 'alcohol', 'alecbaldwin', 'alex', 'alexkendrick',
       'alfredhitchcock', 'alfredmolina', 'ali', 'alic', 'alice', 'alien',
       'alieninvas', 'alienlife', 'alienplanet', 'aliens', 'alik', 'aliv',
       'alive', 'allen', 'alli', 'allianc', 'allow', 'alon', 'alongsid',
       'alpacino', 'alpha', 'alreadi', 'alter', 'altern', 'alway',
       'alyssa', 'alzheimer', 'amanda', 'amandapeet', 'amandaseyfri',
       'amateur', 'amaz', 'ambassador', 'ambit', 'ambiti', 'ambul',
       'ambush', 'america', 'american', 'americanabroad',
       'americancivilwar', 'americanfootbal', 'americanfootballplay',
       'amid', 'amidst', 'amnesia', 'amp', 'amsterdam', 'amus',
       'amusementpark', 'amy', 'amyadam', 'amysmart', 'ana', 'anakin',
       'analyst', 'anarchiccomedi', 'ancient', 'ancientrom',
       'ancientworld', 'anderson', 'andi', 'andiemacdowel', 'andrew',
       'android', 'andy', 'andygarcía', 'angel', 'angela',
       'angelabassett', 'angeles', 'angelinajoli', 'anger', 'angle',
       'angri', 'ani', 'anim', 'animalattack', 'animalhorror', 'animals',
       'anjelicahuston', 'ann', 'anna', 'annafari', 'annakendrick',
       'anne', 'annehathaway', 'annemoss', 'annetteben', 'anni', 'annie',
       'anniversari', 'announc', 'annual', 'anonym', 'anoth', 'answer',
       'ant', 'antholog', 'anthoni', 'anthonyanderson', 'anthonyhopkin',
       'anthonymacki', 'anthropomorph', 'anti', 'antic', 'antihero',
       'antiqu', 'antoinefuqua', 'antoniobandera', 'antonyelchin',
       'anyon', 'anyth', 'apart', 'apartheid', 'apartment', 'ape',
       'apocalyps', 'apocalypse', 'apocalypt', 'appar', 'appear', 'appl',
       'apple', 'appoint', 'appreci', 'apprentic', 'approach', 'april',
       'aquarium', 'arab', 'arch', 'archaeologist', 'archeolog', 'archer',
       'architect', 'arctic', 'area', 'aren', 'arena', 'argument', 'aris',
       'aristocrat', 'arm', 'armi', 'armor', 'armsdeal', 'army', 'arnold',
       'arnoldschwarzenegg', 'arrang', 'arrangedmarriag', 'arrest',
       'arriv', 'arrog', 'art', 'arthur', 'artifact', 'artifici',
       'artificialintellig', 'artist', 'ash', 'ashley', 'ashleyjudd',
       'ashtonkutch', 'asia', 'asian', 'asid', 'ask', 'aspect', 'aspir',
       'assassin', 'assault', 'assembl', 'assign', 'assist', 'assistant',
       'associ', 'assum', 'asteroid', 'astronaut', 'asylum', 'atheist',
       'athlet', 'atom', 'atomicbomb', 'attack', 'attacks', 'attempt',
       'attempttoescap', 'attend', 'attent', 'attic', 'attitud',
       'attorney', 'attract', 'auction', 'audienc', 'audit', 'august',
       'aunt', 'austin', 'australia', 'australian', 'author', 'autism',
       'auto', 'automobilerac', 'aveng', 'averag', 'avoid', 'await',
       'awak', 'awaken', 'awar', 'award', 'away', 'awkward', 'awri',
       'awry', 'ax', 'babe', 'babi', 'baby', 'bachelor', 'backdrop',
       'background', 'backpack', 'bad', 'bag', 'bahama', 'bail', 'balanc',
       'ball', 'ballet', 'balloon', 'baltimor', 'ban', 'band', 'bandit',
       'bangkok', 'banish', 'bank', 'banker', 'bankrobb', 'bankrobberi',
       'bar', 'barbrastreisand', 'bare', 'bargain', 'barn', 'barney',
       'baron', 'barri', 'barrylevinson', 'barrysonnenfeld', 'bas',
       'base', 'basebal', 'basedoncomicbook', 'basedongraphicnovel',
       'basedonnovel', 'basedonplay', 'basedonstagemus', 'basedontrueev',
       'basedontruestori', 'basedontvseri', 'basedonvideogam',
       'basedonyoungadultnovel', 'basement', 'basketbal', 'basketball',
       'bat', 'batman', 'battl', 'battle', 'battlefield', 'bay', 'beach',
       'beam', 'bear', 'beard', 'beast', 'beat', 'beauti', 'beautiful',
       'beautifulwoman', 'beauty', 'becam', 'becaus', 'becki', 'becom',
       'becominganadult', 'bed', 'bedroom', 'bee', 'beer', 'befor',
       'befriend', 'began', 'begin', 'begins', 'behavior', 'belief',
       'believ', 'bell', 'bella', 'belong', 'belov', 'ben', 'benaffleck',
       'bend', 'beneath', 'benefit', 'benfost', 'beniciodeltoro',
       'benjamin', 'benjaminbratt', 'benkingsley', 'bennett', 'benstil',
       'bent', 'berlin', 'best', 'bestfriend', 'bestfriendsinlov', 'bet',
       'beth', 'betray', 'bettemidl', 'better', 'betti', 'beverli',
       'bibl', 'bid', 'big', 'bigger', 'biggest', 'bike', 'biker',
       'bikini', 'billhad', 'billi', 'billionair', 'billmurray',
       'billnighi', 'billpaxton', 'billpullman'], dtype=object)

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similarity = cosine_similarity(vectors)

In [45]:
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329], shape=(4806,))

In [46]:
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [47]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [48]:
import pickle

In [49]:
pickle.dump(new_df,open('movie.pkl','wb'))

In [50]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [51]:
pickle.dump(similarity,open('similarity.pkl','wb'))